apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: movie
  name: movie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie
      version: v1
  template:
    metadata:
      labels:
        app: movie
        version: v1
    spec:
      containers:
        - command:
            - ./movie
          envFrom:
            - configMapRef:
                name: mongodb
          image: 'danding19931115/movie-micro:v1.1'
          imagePullPolicy: IfNotPresent
          name: movie
          ports:
            - containerPort: 80
              name: movie
          resources: {}
      restartPolicy: Always
