apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crawler-minute
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 60
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            # 在批量任务中不使用sidecar
            sidecar.istio.io/inject: "false"
        spec:
          restartPolicy: Never
          containers:
          - name: crawler-minute
            image: danding19931115/movie-micro:latest
            imagePullPolicy: IfNotPresent
            command: ["./minute_job"]
            envFrom:
            - configMapRef:
                name: mongodb