apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crawler
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 60
  jobTemplate:
    spec:
      template:
        metadata:
            annotations:
              # 在批量任务中不使用sidecar
              sidecar.istio.io/inject: "false"
        spec:
          restartPolicy: OnFailure
          containers:
          - name: crawler
            image: danding19931115/movie-micro:latest
            imagePullPolicy: IfNotPresent
            command: ["./day_job"]
            envFrom:
            - configMapRef:
                name: mongodb