apiVersion: batch/v1
kind: Job
metadata:
  name: crawler-tmp
spec:
    template:
      spec:
        restartPolicy: OnFailure
        containers:
        - name: crawler
          imagePullPolicy: Never
          image: movie-job
          envFrom:
          - configMapRef:
              name: mongodb