apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: talk
    version: v1
  name: talk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: talk
      version: v1
  template:
    metadata:
      labels:
        app: talk
        version: v1
    spec:
      containers:
        - command:
            - ./talk
          envFrom:
            - configMapRef:
                name: mongodb
          image: 'danding19931115/movie-micro:latest'
          imagePullPolicy: IfNotPresent
          name: talk
          ports:
            - containerPort: 80
              name: talk
          resources: {}
      restartPolicy: Always
