# See more at https://istio.io/docs/reference/config/networking/virtual-service/
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: talk
spec:
  hosts:
  - 'talk.chenyingqiao.top'
  - 'movie.lerko.cn'
  gateways:
  - talk-gateway
  http:
    - route:
      - destination:
          host: talk
      corsPolicy:
        allowOrigin:
        - "*"
        allowMethods:
        - GET
        - POST
        - OPTIONS
        allowCredentials: true
        allowHeaders:
        - Content-Type
        - AccessToken
        - X-CSRF-Token
        - Authorization
        - Token
        maxAge: "48h"
      headers:
        response:
          set:
            connection: keep-alive