# See more at https://istio.io/docs/reference/config/networking/virtual-service/
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: talk
spec:
  hosts:
  - 'talk.chenyingqiao.top'
  - 'movie.lerko.cn'
  gateways:
  - talk-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: talk