apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-express
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: root
          envFrom:
            - secretRef:
                name: mongo-express
          image: mongo-express
          name: mongo-express
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
data:
  ME_CONFIG_MONGODB_ADMINPASSWORD: cm9vdA==
kind: Secret
metadata:
  name: mongo-express
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-express
  name: mongo-express
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: mongo-express
