apiVersion: v1
data:
  JWT_SING: lerko
  MONGODB_ADDR: 'mongo:27017'
  MONGODB_DB: movie
  MONGODB_POOLSIZE: '30'
  MONGODB_PWD: root
  MONGODB_TIMEOUT: '10'
  MONGODB_USERNAME: root
  ES_ADDRESS: 'elasticsearch:9200'
  ES_TIMEOUT: '10'
kind: ConfigMap
metadata:
  name: mongodb
