files:
  - loader: k8s
    path: auth/deployment.yaml
  - loader: k8s
    path: auth/service.yaml
  - loader: k8s
    path: base-facilities/mongo/deployment.yaml
  - loader: k8s
    path: base-facilities/mongo/mongo-express.yaml
  - loader: k8s
    path: base-facilities/mongo/secret.yaml
  - loader: k8s
    path: base-facilities/mongo/service.yaml
  - loader: k8s
    path: config.yaml
  - loader: k8s
    path: movie/deployment.yaml
  - loader: k8s
    path: movie/service.yaml
  - loader: k8s
    path: server/deployment.yaml
  - loader: k8s
    path: server/service.yaml
  - loader: k8s
    path: talk/deployment.yaml
  - loader: k8s
    path: talk/service.yaml
nodes:
  - kind: Deployment
    name: auth
    plugin: kubernetes-deployment
    position:
      x: 1009
      y: 40
  - kind: Service
    name: auth
    plugin: kubernetes-service
    position:
      x: 1247
      y: 40
  - kind: Deployment
    name: mongo
    plugin: kubernetes-mongodb-deployment
    position:
      x: 40
      y: 40
  - kind: Deployment
    name: mongo-express
    plugin: kubernetes-mongodb-deployment
    position:
      x: 520
      y: 40
  - kind: Secret
    name: mongo-express
    plugin: kubernetes-secret
    position:
      x: 720
      y: 240
  - kind: Service
    name: mongo-express
    plugin: kubernetes-service
    position:
      x: 800
      y: 40
  - kind: Secret
    name: mongo
    plugin: kubernetes-secret
    position:
      x: 1120
      y: 240
  - kind: Service
    name: mongo
    plugin: kubernetes-service
    position:
      x: 320
      y: 40
  - kind: ConfigMap
    name: mongodb
    plugin: kubernetes-config-map
    position:
      x: 480
      y: 240
  - kind: Deployment
    name: movie
    plugin: kubernetes-deployment
    position:
      x: 1440
      y: 40
  - kind: Service
    name: movie
    plugin: kubernetes-service
    position:
      x: 1678
      y: 40
  - kind: Deployment
    name: server
    plugin: kubernetes-deployment
    position:
      x: 1880
      y: 40
  - kind: Service
    name: server
    plugin: kubernetes-service
    position:
      x: 2118
      y: 40
  - kind: Deployment
    name: talk
    plugin: kubernetes-deployment
    position:
      x: 40
      y: 240
  - kind: Service
    name: talk
    plugin: kubernetes-service
    position:
      x: 278
      y: 240
version: '1'
