files:
  - loader: k8s
    path: auth/deployment.yaml
  - loader: k8s
    path: auth/service.yaml
  - loader: k8s
    path: base-facilities/mongo/deployment.yaml
  - loader: k8s
    path: base-facilities/mongo/mongo-express.yaml
  - loader: k8s
    path: base-facilities/mongo/secret.yaml
  - loader: k8s
    path: base-facilities/mongo/service.yaml
  - loader: k8s
    path: config.yaml
  - loader: k8s
    path: movie/deployment.yaml
  - loader: k8s
    path: movie/service.yaml
  - loader: k8s
    path: server/deployment.yaml
  - loader: k8s
    path: server/service.yaml
  - loader: k8s
    path: talk/deployment.yaml
  - loader: k8s
    path: talk/service.yaml
nodes:
  - kind: Deployment
    name: auth
    plugin: kubernetes-deployment
    position:
      x: 346
      y: 40
  - kind: Service
    name: auth
    plugin: kubernetes-service
    position:
      x: 584
      y: 40
  - kind: Deployment
    name: mongo
    plugin: kubernetes-mongodb-deployment
    position:
      x: 40
      y: 40
  - kind: Deployment
    name: mongo-express
    plugin: kubernetes-mongodb-deployment
    position:
      x: 600
      y: 200
  - kind: Secret
    name: mongo-express
    plugin: kubernetes-secret
    position:
      x: 40
      y: 800
  - kind: Service
    name: mongo-express
    plugin: kubernetes-service
    position:
      x: 880
      y: 200
  - kind: Secret
    name: mongo
    plugin: kubernetes-secret
    position:
      x: 440
      y: 880
  - kind: Service
    name: mongo
    plugin: kubernetes-service
    position:
      x: 320
      y: 240
  - kind: ConfigMap
    name: mongodb
    plugin: kubernetes-config-map
    position:
      x: 480
      y: 600
  - kind: Deployment
    name: movie
    plugin: kubernetes-deployment
    position:
      x: 40
      y: 240
  - kind: Service
    name: movie
    plugin: kubernetes-service
    position:
      x: 278
      y: 440
  - kind: Deployment
    name: server
    plugin: kubernetes-deployment
    position:
      x: 480
      y: 400
  - kind: Service
    name: server
    plugin: kubernetes-service
    position:
      x: 718
      y: 400
  - kind: Deployment
    name: talk
    plugin: kubernetes-deployment
    position:
      x: 40
      y: 440
  - kind: Service
    name: talk
    plugin: kubernetes-service
    position:
      x: 278
      y: 640
version: '1'
