export MONGODB_USERNAME=root
export MONGODB_PWD=root
export MONGODB_ADDR=mongo:27017
export MONGODB_DB=test
export MONGODB_TIMEOUT=10
export MONGODB_POOLSIZE=30

export ATUH_SERVICE_HOST=127.0.0.1
export ATUH_SERVICE_PORT=50060